version: '3.8'

services:
  web:
    build: .
    container_name: internship_tracker
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped
